language: generic

sudo: required
services:
    - docker

before_install:
    - docker build -t akshardhee/docker-react -f Dockerfile.dev .
    
script:
  - docker run -e CI=true akshardhee/docker-react npm run test
  