language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t mbc23/docker-react -f dockerfile.dev .
    
script:
  - docker run -e CI=true mbc23/docker-react npm run test
